import type { Recipe, RecipeSummary, Tag } from '@/types';

// Tags
export const cuisineTags: Tag[] = [
  { id: 'c1', uid: 'italian', name: 'Italian' },
  { id: 'c2', uid: 'indian', name: 'Indian' },
  { id: 'c3', uid: 'mediterranean', name: 'Mediterranean' },
  { id: 'c4', uid: 'mexican', name: 'Mexican' },
  { id: 'c5', uid: 'french', name: 'French' },
];

export const ingredientTags: Tag[] = [
  { id: 'i1', uid: 'chicken', name: 'Chicken' },
  { id: 'i2', uid: 'pasta', name: 'Pasta' },
  { id: 'i3', uid: 'salmon', name: 'Salmon' },
  { id: 'i4', uid: 'mushroom', name: 'Mushroom' },
  { id: 'i5', uid: 'chocolate', name: 'Chocolate' },
  { id: 'i6', uid: 'beef', name: 'Beef' },
  { id: 'i7', uid: 'eggs', name: 'Eggs' },
  { id: 'i8', uid: 'tomato', name: 'Tomato' },
];

export const typeTags: Tag[] = [
  { id: 't1', uid: 'main-course', name: 'Main Course' },
  { id: 't2', uid: 'dessert', name: 'Dessert' },
  { id: 't3', uid: 'salad', name: 'Salad' },
  { id: 't4', uid: 'soup', name: 'Soup' },
];

export const seasonTags: Tag[] = [
  { id: 's1', uid: 'fall', name: 'Fall' },
  { id: 's2', uid: 'winter', name: 'Winter' },
  { id: 's3', uid: 'spring', name: 'Spring' },
  { id: 's4', uid: 'summer', name: 'Summer' },
  { id: 's5', uid: 'year-round', name: 'Year Round' },
];

// Full recipe data
export const recipes: Recipe[] = [
  {
    id: '1',
    uid: 'pasta-carbonara',
    title: 'Pasta Carbonara',
    prep_minutes: 15,
    total_minutes: 30,
    servings: 4,
    weekday: false,
    notes: "The key is to remove the pan from heat before adding eggs so they don't scramble.",
    source: 'Adapted from Serious Eats',
    cuisine_tags: [cuisineTags[0]],
    ingredient_tags: [ingredientTags[1], ingredientTags[6]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[1]],
    related_recipes: [
      { id: '5', uid: 'mushroom-risotto', title: 'Mushroom Risotto' },
    ],
    ingredients: [
      { type: 'ingredient', text: '400g spaghetti or rigatoni', aisle: 'Pasta' },
      { type: 'ingredient', text: '200g guanciale or pancetta, diced', aisle: 'Meat' },
      { type: 'ingredient', text: '4 large eggs + 2 yolks', aisle: 'Dairy' },
      { type: 'ingredient', text: '100g Pecorino Romano, finely grated', aisle: 'Cheese' },
      { type: 'ingredient', text: '50g Parmesan, finely grated', aisle: 'Cheese' },
      { type: 'ingredient', text: 'Freshly ground black pepper', aisle: 'Spices' },
      { type: 'ingredient', text: 'Kosher salt', aisle: 'Spices' },
    ],
    instructions: [
      { type: 'instruction', text: 'Bring a large pot of salted water to a boil. Cook pasta until just al dente, reserving 1 cup of pasta water before draining.' },
      { type: 'instruction', text: 'Meanwhile, cook guanciale in a large skillet over medium heat until crisp. Remove from heat and let cool slightly.' },
      { type: 'instruction', text: 'Whisk together eggs, yolks, and cheeses in a bowl. Season generously with black pepper.' },
      { type: 'instruction', text: 'Add drained pasta to the skillet off heat. Pour egg mixture over pasta and toss vigorously, adding pasta water a splash at a time until sauce is creamy and clings to pasta.' },
      { type: 'instruction', text: 'Serve immediately with extra cheese and black pepper.' },
    ],
  },
  {
    id: '2',
    uid: 'chicken-tikka-masala',
    title: 'Chicken Tikka Masala',
    prep_minutes: 30,
    total_minutes: 60,
    servings: 6,
    weekday: false,
    source: 'Adapted from Kenji Alt-Lopez',
    cuisine_tags: [cuisineTags[1]],
    ingredient_tags: [ingredientTags[0]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[0]],
    related_recipes: [],
    ingredients: [
      { type: 'heading', text: 'Marinade' },
      { type: 'ingredient', text: '900g boneless chicken thighs, cut into 2-inch pieces', aisle: 'Meat' },
      { type: 'ingredient', text: '1 cup full-fat yogurt', aisle: 'Dairy' },
      { type: 'ingredient', text: '2 tbsp lemon juice', aisle: 'Produce' },
      { type: 'ingredient', text: '2 tsp each: cumin, coriander, garam masala, paprika', aisle: 'Spices' },
      { type: 'heading', text: 'Sauce' },
      { type: 'ingredient', text: '2 tbsp butter + 2 tbsp oil', aisle: 'Baking' },
      { type: 'ingredient', text: '1 large onion, diced', aisle: 'Produce' },
      { type: 'ingredient', text: '6 garlic cloves, minced', aisle: 'Produce' },
      { type: 'ingredient', text: '2-inch piece ginger, grated', aisle: 'Produce' },
      { type: 'ingredient', text: '1 can (800g) crushed tomatoes', aisle: 'Soup' },
      { type: 'ingredient', text: '1 cup heavy cream', aisle: 'Dairy' },
    ],
    instructions: [
      { type: 'heading', text: 'Marinate & Cook Chicken' },
      { type: 'instruction', text: 'Combine marinade ingredients and coat chicken. Refrigerate at least 2 hours, up to overnight.' },
      { type: 'instruction', text: 'Broil or grill chicken until charred and cooked through, about 8 minutes. Set aside.' },
      { type: 'heading', text: 'Make Sauce' },
      { type: 'instruction', text: 'Cook onion in butter and oil over medium heat until golden, 15 minutes. Add garlic and ginger, cook 2 minutes.' },
      { type: 'instruction', text: 'Add spices and toast 1 minute. Add tomatoes and simmer 20 minutes.' },
      { type: 'instruction', text: 'Blend sauce until smooth. Return to pan, add cream and chicken. Simmer 10 minutes. Season to taste.' },
    ],
  },
  {
    id: '3',
    uid: 'greek-salad',
    title: 'Greek Salad',
    prep_minutes: 15,
    total_minutes: 15,
    servings: 4,
    weekday: true,
    cuisine_tags: [cuisineTags[2]],
    ingredient_tags: [ingredientTags[7]],
    type_tags: [typeTags[2]],
    season_tags: [seasonTags[3]],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '1 large English cucumber, roughly chopped', aisle: 'Produce' },
      { type: 'ingredient', text: '4 large tomatoes, roughly chopped', aisle: 'Produce' },
      { type: 'ingredient', text: '1 red onion, thinly sliced', aisle: 'Produce' },
      { type: 'ingredient', text: '1 cup Kalamata olives', aisle: 'World Aisle' },
      { type: 'ingredient', text: '200g block feta cheese', aisle: 'Cheese' },
      { type: 'ingredient', text: '¼ cup extra virgin olive oil', aisle: 'World Aisle' },
      { type: 'ingredient', text: '2 tbsp red wine vinegar', aisle: 'World Aisle' },
      { type: 'ingredient', text: 'Dried oregano, salt, pepper', aisle: 'Spices' },
    ],
    instructions: [
      { type: 'instruction', text: 'Combine cucumber, tomatoes, onion, and olives in a large bowl.' },
      { type: 'instruction', text: 'Whisk together olive oil, vinegar, oregano, salt, and pepper. Pour over vegetables and toss.' },
      { type: 'instruction', text: 'Place feta block on top (or crumble over). Drizzle with a little extra olive oil and dried oregano.' },
    ],
  },
  {
    id: '4',
    uid: 'pan-seared-salmon',
    title: 'Pan-Seared Salmon',
    prep_minutes: 5,
    total_minutes: 20,
    servings: 2,
    weekday: true,
    cuisine_tags: [cuisineTags[4]],
    ingredient_tags: [ingredientTags[2]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[2]],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '2 salmon fillets (6 oz each), skin-on', aisle: 'Seafood' },
      { type: 'ingredient', text: '2 tbsp olive oil', aisle: 'World Aisle' },
      { type: 'ingredient', text: '2 tbsp butter', aisle: 'Dairy' },
      { type: 'ingredient', text: '3 garlic cloves, smashed', aisle: 'Produce' },
      { type: 'ingredient', text: 'Fresh thyme and rosemary', aisle: 'Produce' },
      { type: 'ingredient', text: '1 lemon', aisle: 'Produce' },
      { type: 'ingredient', text: 'Salt and pepper', aisle: 'Spices' },
    ],
    instructions: [
      { type: 'instruction', text: 'Pat salmon dry and season generously with salt and pepper on both sides.' },
      { type: 'instruction', text: 'Heat oil in a stainless or cast-iron skillet over high heat until smoking. Place salmon skin-side down and press firmly for 10 seconds.' },
      { type: 'instruction', text: 'Cook without moving until skin is crisp and releases easily, about 4 minutes. Flip and add butter, garlic, and herbs.' },
      { type: 'instruction', text: 'Baste with butter for 1–2 minutes until salmon reaches desired doneness. Squeeze lemon over and serve immediately.' },
    ],
  },
  {
    id: '5',
    uid: 'mushroom-risotto',
    title: 'Mushroom Risotto',
    prep_minutes: 15,
    total_minutes: 45,
    servings: 4,
    weekday: false,
    cuisine_tags: [cuisineTags[0]],
    ingredient_tags: [ingredientTags[3]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[0]],
    related_recipes: [{ id: '1', uid: 'pasta-carbonara', title: 'Pasta Carbonara' }],
    ingredients: [
      { type: 'ingredient', text: '300g Arborio rice', aisle: 'World Aisle' },
      { type: 'ingredient', text: '500g mixed mushrooms, sliced', aisle: 'Produce' },
      { type: 'ingredient', text: '1.2L warm chicken or vegetable stock', aisle: 'Soup' },
      { type: 'ingredient', text: '1 large shallot, finely diced', aisle: 'Produce' },
      { type: 'ingredient', text: '3 garlic cloves, minced', aisle: 'Produce' },
      { type: 'ingredient', text: '150ml dry white wine', aisle: 'Beer and Wine' },
      { type: 'ingredient', text: '60g cold butter, cubed', aisle: 'Dairy' },
      { type: 'ingredient', text: '60g Parmesan, grated', aisle: 'Cheese' },
      { type: 'ingredient', text: 'Fresh thyme, salt, pepper', aisle: 'Produce' },
    ],
    instructions: [
      { type: 'instruction', text: 'Sauté mushrooms in butter over high heat until golden and any liquid evaporates. Season and set aside.' },
      { type: 'instruction', text: 'In the same pan, cook shallot over medium heat until soft. Add garlic and rice, stir to coat in fat for 2 minutes.' },
      { type: 'instruction', text: 'Add wine and stir until absorbed. Add warm stock one ladle at a time, stirring constantly and waiting for absorption before adding more, about 18 minutes.' },
      { type: 'instruction', text: 'Remove from heat. Stir in cold butter and Parmesan vigorously until creamy. Fold in mushrooms. Rest 2 minutes before serving.' },
    ],
  },
  {
    id: '6',
    uid: 'beef-tacos',
    title: 'Beef Tacos',
    prep_minutes: 10,
    total_minutes: 30,
    servings: 4,
    weekday: true,
    cuisine_tags: [cuisineTags[3]],
    ingredient_tags: [ingredientTags[5]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[4]],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '500g ground beef (80/20)', aisle: 'Meat' },
      { type: 'ingredient', text: '1 tbsp each: cumin, chili powder, smoked paprika', aisle: 'Spices' },
      { type: 'ingredient', text: '1 tsp garlic powder, onion powder', aisle: 'Spices' },
      { type: 'ingredient', text: '8 corn or flour tortillas', aisle: 'World Aisle' },
      { type: 'ingredient', text: 'Shredded cheese, salsa, sour cream', aisle: 'Dairy' },
      { type: 'ingredient', text: 'Shredded lettuce, diced tomato, lime', aisle: 'Produce' },
    ],
    instructions: [
      { type: 'instruction', text: 'Cook beef in a skillet over medium-high heat, breaking apart, until browned. Drain excess fat.' },
      { type: 'instruction', text: 'Add spices and ¼ cup water. Simmer 3 minutes until sauce thickens. Season with salt.' },
      { type: 'instruction', text: 'Warm tortillas in a dry pan. Fill with beef and desired toppings.' },
    ],
  },
  {
    id: '7',
    uid: 'lemon-herb-roasted-chicken',
    title: 'Lemon Herb Roasted Chicken',
    prep_minutes: 20,
    total_minutes: 90,
    servings: 4,
    weekday: false,
    cuisine_tags: [cuisineTags[4]],
    ingredient_tags: [ingredientTags[0]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[2]],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '1 whole chicken (1.8kg)', aisle: 'Meat' },
      { type: 'ingredient', text: '1 lemon, halved', aisle: 'Produce' },
      { type: 'ingredient', text: '1 head of garlic, halved crosswise', aisle: 'Produce' },
      { type: 'ingredient', text: 'Fresh rosemary, thyme, and sage', aisle: 'Produce' },
      { type: 'ingredient', text: '4 tbsp softened butter', aisle: 'Dairy' },
      { type: 'ingredient', text: 'Salt and black pepper', aisle: 'Spices' },
    ],
    instructions: [
      { type: 'instruction', text: 'Pat chicken dry inside and out. Mix softened butter with chopped herbs, zest of half lemon, salt, and pepper. Rub all over and under the skin.' },
      { type: 'instruction', text: 'Stuff cavity with lemon halves and garlic. Tie legs together. Let sit at room temperature 30 minutes.' },
      { type: 'instruction', text: 'Roast at 220°C (425°F) for 60–75 minutes, until juices run clear and skin is deep golden. Rest 15 minutes before carving.' },
    ],
  },
  {
    id: '8',
    uid: 'roasted-vegetable-soup',
    title: 'Roasted Vegetable Soup',
    prep_minutes: 20,
    total_minutes: 60,
    servings: 6,
    weekday: true,
    ingredient_tags: [ingredientTags[7]],
    type_tags: [typeTags[3]],
    season_tags: [seasonTags[1]],
    cuisine_tags: [],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '1 butternut squash, cubed', aisle: 'Produce' },
      { type: 'ingredient', text: '3 large carrots, chopped', aisle: 'Produce' },
      { type: 'ingredient', text: '2 red peppers, quartered', aisle: 'Produce' },
      { type: 'ingredient', text: '1 large onion, quartered', aisle: 'Produce' },
      { type: 'ingredient', text: '6 garlic cloves', aisle: 'Produce' },
      { type: 'ingredient', text: '1L vegetable stock', aisle: 'Soup' },
      { type: 'ingredient', text: '400ml coconut milk', aisle: 'World Aisle' },
      { type: 'ingredient', text: 'Olive oil, smoked paprika, cumin, salt', aisle: 'Spices' },
    ],
    instructions: [
      { type: 'instruction', text: 'Toss vegetables with olive oil and spices on a sheet pan. Roast at 200°C until caramelized, about 35 minutes.' },
      { type: 'instruction', text: 'Transfer roasted vegetables to a large pot. Add stock and coconut milk. Bring to a simmer for 10 minutes.' },
      { type: 'instruction', text: 'Blend until smooth. Adjust seasoning and consistency with additional stock as needed.' },
    ],
  },
  {
    id: '9',
    uid: 'chocolate-lava-cake',
    title: 'Chocolate Lava Cake',
    prep_minutes: 15,
    total_minutes: 25,
    servings: 4,
    weekday: false,
    cuisine_tags: [cuisineTags[4]],
    ingredient_tags: [ingredientTags[4]],
    type_tags: [typeTags[1]],
    season_tags: [seasonTags[4]],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '170g dark chocolate (70%), chopped', aisle: 'Baking' },
      { type: 'ingredient', text: '115g butter, plus more for ramekins', aisle: 'Dairy' },
      { type: 'ingredient', text: '2 whole eggs + 2 yolks', aisle: 'Dairy' },
      { type: 'ingredient', text: '60g caster sugar', aisle: 'Baking' },
      { type: 'ingredient', text: '1 tsp vanilla extract', aisle: 'Baking' },
      { type: 'ingredient', text: '2 tbsp all-purpose flour', aisle: 'Baking' },
      { type: 'ingredient', text: 'Cocoa powder for dusting', aisle: 'Baking' },
    ],
    instructions: [
      { type: 'instruction', text: 'Butter 4 ramekins and dust with cocoa powder. Melt chocolate and butter together, stirring until smooth. Cool slightly.' },
      { type: 'instruction', text: 'Whisk eggs, yolks, and sugar until pale and slightly thickened, about 2 minutes. Fold in chocolate mixture and vanilla. Sift in flour and fold until just combined.' },
      { type: 'instruction', text: 'Divide batter among ramekins. Can be refrigerated up to 1 day at this point.' },
      { type: 'instruction', text: 'Bake at 220°C (425°F) for 10–12 minutes until edges are set but center still jiggles. Let rest 1 minute, then invert onto plates and serve immediately.' },
    ],
  },
  {
    id: '10',
    uid: 'shakshuka',
    title: 'Shakshuka',
    prep_minutes: 10,
    total_minutes: 35,
    servings: 4,
    weekday: true,
    cuisine_tags: [cuisineTags[2]],
    ingredient_tags: [ingredientTags[6], ingredientTags[7]],
    type_tags: [typeTags[0]],
    season_tags: [seasonTags[4]],
    related_recipes: [],
    ingredients: [
      { type: 'ingredient', text: '2 cans (400g each) diced tomatoes', aisle: 'Soup' },
      { type: 'ingredient', text: '1 red pepper, diced', aisle: 'Produce' },
      { type: 'ingredient', text: '1 onion, diced', aisle: 'Produce' },
      { type: 'ingredient', text: '4 garlic cloves, minced', aisle: 'Produce' },
      { type: 'ingredient', text: '1 tsp each: cumin, paprika, chili flakes', aisle: 'Spices' },
      { type: 'ingredient', text: '6 large eggs', aisle: 'Dairy' },
      { type: 'ingredient', text: 'Feta cheese and fresh parsley for serving', aisle: 'Cheese' },
    ],
    instructions: [
      { type: 'instruction', text: 'Cook onion and pepper in olive oil over medium heat until soft, 8 minutes. Add garlic and spices, cook 1 minute.' },
      { type: 'instruction', text: 'Add tomatoes and season with salt. Simmer until sauce thickens slightly, about 10 minutes.' },
      { type: 'instruction', text: 'Make wells in the sauce and crack an egg into each. Cover and cook until whites are set but yolks are still runny, 6–8 minutes.' },
      { type: 'instruction', text: 'Top with crumbled feta and fresh parsley. Serve from the pan with crusty bread.' },
    ],
  },
];

// Homepage curations
export const nextRecipes: RecipeSummary[] = [
  { id: '2', uid: 'chicken-tikka-masala', title: 'Chicken Tikka Masala' },
  { id: '5', uid: 'mushroom-risotto', title: 'Mushroom Risotto' },
  { id: '7', uid: 'lemon-herb-roasted-chicken', title: 'Lemon Herb Roasted Chicken' },
];

export const favoriteRecipes: RecipeSummary[] = [
  { id: '1', uid: 'pasta-carbonara', title: 'Pasta Carbonara' },
  { id: '4', uid: 'pan-seared-salmon', title: 'Pan-Seared Salmon' },
  { id: '9', uid: 'chocolate-lava-cake', title: 'Chocolate Lava Cake' },
];

export const recentRecipes: RecipeSummary[] = recipes.slice(5, 10).map(({ id, uid, title }) => ({ id, uid, title }));

export const randomRecipes: RecipeSummary[] = [recipes[0], recipes[2], recipes[3], recipes[8]].map(({ id, uid, title }) => ({ id, uid, title }));

// Cook next list (used for grocery list)
export const cookNextRecipes = [recipes[1], recipes[4], recipes[6]];
